@startuml
skinparam componentStyle rectangle
top to bottom direction
' 使用垂直布局

[用户界面] as user_interface

rectangle "用户核心功能" {
  [用户注册与验证] as register
  [用户登录认证] as login
  [用户信息管理] as profile
}
note top of register
  邮箱验证、验证码校验
end note

rectangle "权限与审计" {
  [权限控制] as permission
  [用户行为记录] as log
}

user_interface --> register
user_interface --> login
user_interface --> profile
user_interface --> permission

register --> "用户数据库"
login --> "用户数据库"
profile --> "用户数据库"
permission --> "用户数据库"
log --> "日志存储"


note bottom of login
  登录认证、Token生成
end note

note bottom of profile
  资料修改、头像管理
end note

note top of permission
  角色判断、接口权限控制
end note

note top of log
  操作日志记录
end note

'title 图2 用户管理子系统
@enduml
