###

# 用户登录 获取验证码
# id 学号 10位整数
POST http://localhost:8090/api/login
Content-Type: application/json

{
    "id": 2235062316
}
###
# 核对验证码
# code 验证码
POST http://localhost:8090/api/login/verify
Content-Type: application/json

{
    "code": "429159"
}
###

GET http://localhost:8090/api/user?targetUserId=2235062316

###
POST http://localhost:8090/api/user/post/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="D:\iCloudPhotos\IMG_0354.JPG"
Content-Type: image/jpeg

< D:\iCloudPhotos\IMG_0354.JPG
--WebAppBoundary--
###